# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Improve for VI keymap
KEYTIMEOUT=1
TERM='screen-256color'
EDITOR=vi

# Environemnt setup
eval "$(nodenv init -)"
eval "$(rbenv init -)"
eval "$(pyenv init -)"

# Customize to your needs...
# Functions
function take() {
  mkdir -p $@ && cd ${@:$#}
}

# Aliases
alias g='git'
alias y='yarn'
alias ya='yarn add'
alias yad='yarn add --dev'
alias ccat='pygmentize -O style=tomorrownight -f console256 -g'
alias cd.='cd .'
alias cd..='cd ..'

# tmux/tmuxinator
alias mux=tmuxinator

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ -f ~/.p10k.zsh ]] && source ~/.p10k.zsh

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
