# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Improve VI keymaps
KEYTIMEOUT=1
TERM='screen-256color'
EDITOR=vi

export GPG_TTY=$(tty)

export ANDROID_HOME=$HOME/Library/Android/sdk
export PATH=$PATH:$ANDROID_HOME/emulator
export PATH=$PATH:$ANDROID_HOME/tools
export PATH=$PATH:$ANDROID_HOME/tools/bin
export PATH=$PATH:$ANDROID_HOME/platform-tools

# Environemnt setup
eval "$(nodenv init -)"
eval "$(rbenv init -)"
eval "$(pyenv init -)"

# AWS setup
alias aws-unset='unset AWS_SECURITY_TOKEN AWS_SESSION_TOKEN AWS_SECRET_ACCESS_KEY AWS_ACCESS_KEY_ID AWS_PROFILE'
aws-set () {
  aws-unset
  AWS_PROFILE=${1-st6_sandbox}
  echo Setting AWS profile: $AWS_PROFILE
  eval $(assume-role $AWS_PROFILE)
}

# Functions
function take() {
  mkdir -p $@ && cd ${@:$#}
}

function mp3() {
  ffmpeg -i $1 -vn -ar 44100 -ac 2 -b:a 192k $2
}

# Aliases
alias todo='vim ~/Desktop/todo.txt'
alias t='tmux attach || tmux new-session'
alias bex='bundle exec'
alias g='git'
alias y='yarn'
alias ys='yarn start'
alias yl='yarn lint'
alias yt='yarn test'
alias ytc='yarn test --coverage'
alias ytw='yarn test --watch'
alias ya='yarn add'
alias yae='yarn add --exact'
alias yad='yarn add --dev'
alias yaed='yarn add --exact --dev'
alias yade='yarn add --exact --dev'
alias port='lsof -nP -iTCP -sTCP:LISTEN'
alias gb='git branch --show-current | pbcopy'
alias j='pbpaste | jq . | pbcopy'

# Dock
alias dock-left='defaults write com.apple.dock orientation left; killall Dock'
alias dock-right='defaults write com.apple.dock orientation right; killall Dock'

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ -f ~/.p10k.zsh ]] && source ~/.p10k.zsh

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
